title: Finance Wallet Codex
description: Sovereign lineage, crest shimmer, and ceremonial broadcasts
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-remote-theme   